name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt-cache search libsdl && sudo apt-get install libsdl1.2-dev libjack-dev -y 
    - name: make
      run: make -f makefile.linux
    - name: make zip
      run: >
        cd release/distrib && zip -vr ptk_v2.5.4_linux_win32.zip *
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: release/distrib/ptk_v2.5.4_linux.zip
