name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: apt-cache search libsdl && sudo apt-get install libsdl1.2-dev libjack-dev -y 
    - name: make
      run: make -f makefile.linux
    - name: make zip
      run: |
        cd release/distrib
        zip -vr ptk_v2.5.4_crossplatform.zip *
    - uses: ncipollo/release-action@v1
      with:
        artifacs: release/distrib/ptk_v2.5.4_crossplatform.zip
        token: ${{ secrets.GITHUB_TOKEN }}    

